void main(){
  throwError();
}
void throwError() {
  throw Exception('This function always throws an error.');
}